services:
  mcp-server-accwiki:
    build:
      context: ..
      dockerfile: mcp-server-accwiki/Dockerfile
    container_name: mcp-server-accwiki
    ports:
      - "8001:8001"  # MCP server port
    command: ["python3", "server.py"]
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=
      - EMBED_MODEL=BAAI/bge-m3
      - USE_CUDA=auto
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - HF_TOKEN=${HF_TOKEN:-}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server.py:/app/server.py
      - ./query_knowledge_graph.py:/app/query_knowledge_graph.py
      - ./embeddings.py:/app/embeddings.py
      - ./requirements.txt:/app/requirements.txt
      - model_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - neo4j
    restart: unless-stopped
    stdin_open: false
    tty: false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  neo4j:
    image: neo4j:5.20
    container_name: neo4j-mcp
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=512M
    volumes:
      - knowledge_graph_rag_neo4j_data:/data
      - knowledge_graph_rag_neo4j_logs:/logs
      - knowledge_graph_rag_neo4j_import:/var/lib/neo4j/import
      - knowledge_graph_rag_neo4j_plugins:/plugins
    restart: unless-stopped

volumes:
  knowledge_graph_rag_neo4j_data:
    external: true
  knowledge_graph_rag_neo4j_logs:
    external: true
  knowledge_graph_rag_neo4j_import:
    external: true
  knowledge_graph_rag_neo4j_plugins:
    external: true
  model_cache:
    external: false
